// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NetMessage.proto

package com.freddy.im.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NetMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>string messageid = 1;</code>
     */
    String getMessageid();
    /**
     * <pre>
     * 消息体 messageid
     * </pre>
     *
     * <code>string messageid = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageidBytes();

    /**
     * <pre>
     *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
     * </pre>
     *
     * <code>string messageseqid = 2;</code>
     */
    String getMessageseqid();
    /**
     * <pre>
     *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
     * </pre>
     *
     * <code>string messageseqid = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageseqidBytes();

    /**
     * <pre>
     *ÿ��ҵ��ϵͳһ��gamemoduleid        
     * </pre>
     *
     * <code>string gamemoduleid = 3;</code>
     */
    String getGamemoduleid();
    /**
     * <pre>
     *ÿ��ҵ��ϵͳһ��gamemoduleid        
     * </pre>
     *
     * <code>string gamemoduleid = 3;</code>
     */
    com.google.protobuf.ByteString
        getGamemoduleidBytes();

    /**
     * <pre>
     *������  
     * </pre>
     *
     * <code>string errorcode = 4;</code>
     */
    String getErrorcode();
    /**
     * <pre>
     *������  
     * </pre>
     *
     * <code>string errorcode = 4;</code>
     */
    com.google.protobuf.ByteString
        getErrorcodeBytes();

    /**
     * <pre>
     *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
     * </pre>
     *
     * <code>string messagetype = 5;</code>
     */
    String getMessagetype();
    /**
     * <pre>
     *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
     * </pre>
     *
     * <code>string messagetype = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessagetypeBytes();

    /**
     * <pre>
     *����ʱ���
     * </pre>
     *
     * <code>string sendtime = 6;</code>
     */
    String getSendtime();
    /**
     * <pre>
     *����ʱ���
     * </pre>
     *
     * <code>string sendtime = 6;</code>
     */
    com.google.protobuf.ByteString
        getSendtimeBytes();

    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
     * </pre>
     *
     * <code>string frommoduleid = 7;</code>
     */
    String getFrommoduleid();
    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
     * </pre>
     *
     * <code>string frommoduleid = 7;</code>
     */
    com.google.protobuf.ByteString
        getFrommoduleidBytes();

    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
     * </pre>
     *
     * <code>string tomoduleid = 8;</code>
     */
    String getTomoduleid();
    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
     * </pre>
     *
     * <code>string tomoduleid = 8;</code>
     */
    com.google.protobuf.ByteString
        getTomoduleidBytes();

    /**
     * <pre>
     *�û�id  
     * </pre>
     *
     * <code>string playerid = 9;</code>
     */
    String getPlayerid();
    /**
     * <pre>
     *�û�id  
     * </pre>
     *
     * <code>string playerid = 9;</code>
     */
    com.google.protobuf.ByteString
        getPlayeridBytes();

    /**
     * <pre>
     *�ͻ���ip     
     * </pre>
     *
     * <code>string clientip = 10;</code>
     */
    String getClientip();
    /**
     * <pre>
     *�ͻ���ip     
     * </pre>
     *
     * <code>string clientip = 10;</code>
     */
    com.google.protobuf.ByteString
        getClientipBytes();

    /**
     * <pre>
     *ȫ���˺�id
     * </pre>
     *
     * <code>string accountid = 11;</code>
     */
    String getAccountid();
    /**
     * <pre>
     *ȫ���˺�id
     * </pre>
     *
     * <code>string accountid = 11;</code>
     */
    com.google.protobuf.ByteString
        getAccountidBytes();

    /**
     * <pre>
     *��Ϣ������Կ
     * </pre>
     *
     * <code>string secretkey = 12;</code>
     */
    String getSecretkey();
    /**
     * <pre>
     *��Ϣ������Կ
     * </pre>
     *
     * <code>string secretkey = 12;</code>
     */
    com.google.protobuf.ByteString
        getSecretkeyBytes();

    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 13;</code>
     */
    String getToken();
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 13;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *json��ʽ����Ϣ��
     * </pre>
     *
     * <code>string body = 14;</code>
     */
    String getBody();
    /**
     * <pre>
     *json��ʽ����Ϣ��
     * </pre>
     *
     * <code>string body = 14;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code NetMessage}
   */
  public  static final class NetMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NetMessage)
      NetMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetMessage.newBuilder() to construct.
    private NetMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetMessage() {
      messageid_ = "";
      messageseqid_ = "";
      gamemoduleid_ = "";
      errorcode_ = "";
      messagetype_ = "";
      sendtime_ = "";
      frommoduleid_ = "";
      tomoduleid_ = "";
      playerid_ = "";
      clientip_ = "";
      accountid_ = "";
      secretkey_ = "";
      token_ = "";
      body_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              messageid_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              messageseqid_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              gamemoduleid_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              errorcode_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              messagetype_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              sendtime_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              frommoduleid_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              tomoduleid_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              playerid_ = s;
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              clientip_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              accountid_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              secretkey_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Message.internal_static_NetMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_NetMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetMessage.class, Builder.class);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private volatile Object messageid_;
    /**
     * <pre>
     *ҵ�񷽷�messageid  ÿ��ҵ�񷽷�һ��messageid
     * </pre>
     *
     * <code>string messageid = 1;</code>
     */
    public String getMessageid() {
      Object ref = messageid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ҵ�񷽷�messageid  ÿ��ҵ�񷽷�һ��messageid
     * </pre>
     *
     * <code>string messageid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageidBytes() {
      Object ref = messageid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGESEQID_FIELD_NUMBER = 2;
    private volatile Object messageseqid_;
    /**
     * <pre>
     *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
     * </pre>
     *
     * <code>string messageseqid = 2;</code>
     */
    public String getMessageseqid() {
      Object ref = messageseqid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messageseqid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
     * </pre>
     *
     * <code>string messageseqid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageseqidBytes() {
      Object ref = messageseqid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messageseqid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAMEMODULEID_FIELD_NUMBER = 3;
    private volatile Object gamemoduleid_;
    /**
     * <pre>
     *ÿ��ҵ��ϵͳһ��gamemoduleid        
     * </pre>
     *
     * <code>string gamemoduleid = 3;</code>
     */
    public String getGamemoduleid() {
      Object ref = gamemoduleid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        gamemoduleid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ÿ��ҵ��ϵͳһ��gamemoduleid        
     * </pre>
     *
     * <code>string gamemoduleid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGamemoduleidBytes() {
      Object ref = gamemoduleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        gamemoduleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private volatile Object errorcode_;
    /**
     * <pre>
     *������  
     * </pre>
     *
     * <code>string errorcode = 4;</code>
     */
    public String getErrorcode() {
      Object ref = errorcode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errorcode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *������  
     * </pre>
     *
     * <code>string errorcode = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorcodeBytes() {
      Object ref = errorcode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorcode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 5;
    private volatile Object messagetype_;
    /**
     * <pre>
     *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
     * </pre>
     *
     * <code>string messagetype = 5;</code>
     */
    public String getMessagetype() {
      Object ref = messagetype_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        messagetype_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
     * </pre>
     *
     * <code>string messagetype = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessagetypeBytes() {
      Object ref = messagetype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        messagetype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDTIME_FIELD_NUMBER = 6;
    private volatile Object sendtime_;
    /**
     * <pre>
     *����ʱ���
     * </pre>
     *
     * <code>string sendtime = 6;</code>
     */
    public String getSendtime() {
      Object ref = sendtime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sendtime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *����ʱ���
     * </pre>
     *
     * <code>string sendtime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSendtimeBytes() {
      Object ref = sendtime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sendtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMMODULEID_FIELD_NUMBER = 7;
    private volatile Object frommoduleid_;
    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
     * </pre>
     *
     * <code>string frommoduleid = 7;</code>
     */
    public String getFrommoduleid() {
      Object ref = frommoduleid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        frommoduleid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
     * </pre>
     *
     * <code>string frommoduleid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFrommoduleidBytes() {
      Object ref = frommoduleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        frommoduleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOMODULEID_FIELD_NUMBER = 8;
    private volatile Object tomoduleid_;
    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
     * </pre>
     *
     * <code>string tomoduleid = 8;</code>
     */
    public String getTomoduleid() {
      Object ref = tomoduleid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tomoduleid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
     * </pre>
     *
     * <code>string tomoduleid = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTomoduleidBytes() {
      Object ref = tomoduleid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tomoduleid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 9;
    private volatile Object playerid_;
    /**
     * <pre>
     *�û�id  
     * </pre>
     *
     * <code>string playerid = 9;</code>
     */
    public String getPlayerid() {
      Object ref = playerid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        playerid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *�û�id  
     * </pre>
     *
     * <code>string playerid = 9;</code>
     */
    public com.google.protobuf.ByteString
        getPlayeridBytes() {
      Object ref = playerid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        playerid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTIP_FIELD_NUMBER = 10;
    private volatile Object clientip_;
    /**
     * <pre>
     *�ͻ���ip     
     * </pre>
     *
     * <code>string clientip = 10;</code>
     */
    public String getClientip() {
      Object ref = clientip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientip_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *�ͻ���ip     
     * </pre>
     *
     * <code>string clientip = 10;</code>
     */
    public com.google.protobuf.ByteString
        getClientipBytes() {
      Object ref = clientip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTID_FIELD_NUMBER = 11;
    private volatile Object accountid_;
    /**
     * <pre>
     *ȫ���˺�id
     * </pre>
     *
     * <code>string accountid = 11;</code>
     */
    public String getAccountid() {
      Object ref = accountid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accountid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *ȫ���˺�id
     * </pre>
     *
     * <code>string accountid = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAccountidBytes() {
      Object ref = accountid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accountid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECRETKEY_FIELD_NUMBER = 12;
    private volatile Object secretkey_;
    /**
     * <pre>
     *��Ϣ������Կ
     * </pre>
     *
     * <code>string secretkey = 12;</code>
     */
    public String getSecretkey() {
      Object ref = secretkey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        secretkey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��Ϣ������Կ
     * </pre>
     *
     * <code>string secretkey = 12;</code>
     */
    public com.google.protobuf.ByteString
        getSecretkeyBytes() {
      Object ref = secretkey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        secretkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 13;
    private volatile Object token_;
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 13;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 14;
    private volatile Object body_;
    /**
     * <pre>
     *json��ʽ����Ϣ��
     * </pre>
     *
     * <code>string body = 14;</code>
     */
    public String getBody() {
      Object ref = body_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *json��ʽ����Ϣ��
     * </pre>
     *
     * <code>string body = 14;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageid_);
      }
      if (!getMessageseqidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageseqid_);
      }
      if (!getGamemoduleidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gamemoduleid_);
      }
      if (!getErrorcodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorcode_);
      }
      if (!getMessagetypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, messagetype_);
      }
      if (!getSendtimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, sendtime_);
      }
      if (!getFrommoduleidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, frommoduleid_);
      }
      if (!getTomoduleidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tomoduleid_);
      }
      if (!getPlayeridBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, playerid_);
      }
      if (!getClientipBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, clientip_);
      }
      if (!getAccountidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, accountid_);
      }
      if (!getSecretkeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, secretkey_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, token_);
      }
      if (!getBodyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, body_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageid_);
      }
      if (!getMessageseqidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageseqid_);
      }
      if (!getGamemoduleidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gamemoduleid_);
      }
      if (!getErrorcodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorcode_);
      }
      if (!getMessagetypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, messagetype_);
      }
      if (!getSendtimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, sendtime_);
      }
      if (!getFrommoduleidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, frommoduleid_);
      }
      if (!getTomoduleidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tomoduleid_);
      }
      if (!getPlayeridBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, playerid_);
      }
      if (!getClientipBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, clientip_);
      }
      if (!getAccountidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, accountid_);
      }
      if (!getSecretkeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, secretkey_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, token_);
      }
      if (!getBodyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NetMessage)) {
        return super.equals(obj);
      }
      NetMessage other = (NetMessage) obj;

      if (!getMessageid()
          .equals(other.getMessageid())) return false;
      if (!getMessageseqid()
          .equals(other.getMessageseqid())) return false;
      if (!getGamemoduleid()
          .equals(other.getGamemoduleid())) return false;
      if (!getErrorcode()
          .equals(other.getErrorcode())) return false;
      if (!getMessagetype()
          .equals(other.getMessagetype())) return false;
      if (!getSendtime()
          .equals(other.getSendtime())) return false;
      if (!getFrommoduleid()
          .equals(other.getFrommoduleid())) return false;
      if (!getTomoduleid()
          .equals(other.getTomoduleid())) return false;
      if (!getPlayerid()
          .equals(other.getPlayerid())) return false;
      if (!getClientip()
          .equals(other.getClientip())) return false;
      if (!getAccountid()
          .equals(other.getAccountid())) return false;
      if (!getSecretkey()
          .equals(other.getSecretkey())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageid().hashCode();
      hash = (37 * hash) + MESSAGESEQID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageseqid().hashCode();
      hash = (37 * hash) + GAMEMODULEID_FIELD_NUMBER;
      hash = (53 * hash) + getGamemoduleid().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorcode().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessagetype().hashCode();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getSendtime().hashCode();
      hash = (37 * hash) + FROMMODULEID_FIELD_NUMBER;
      hash = (53 * hash) + getFrommoduleid().hashCode();
      hash = (37 * hash) + TOMODULEID_FIELD_NUMBER;
      hash = (53 * hash) + getTomoduleid().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerid().hashCode();
      hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
      hash = (53 * hash) + getClientip().hashCode();
      hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
      hash = (53 * hash) + getAccountid().hashCode();
      hash = (37 * hash) + SECRETKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSecretkey().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NetMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NetMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NetMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NetMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NetMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NetMessage)
        NetMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Message.internal_static_NetMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_NetMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetMessage.class, Builder.class);
      }

      // Construct using com.network.message.web.Message.NetMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        messageid_ = "";

        messageseqid_ = "";

        gamemoduleid_ = "";

        errorcode_ = "";

        messagetype_ = "";

        sendtime_ = "";

        frommoduleid_ = "";

        tomoduleid_ = "";

        playerid_ = "";

        clientip_ = "";

        accountid_ = "";

        secretkey_ = "";

        token_ = "";

        body_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Message.internal_static_NetMessage_descriptor;
      }

      @Override
      public NetMessage getDefaultInstanceForType() {
        return NetMessage.getDefaultInstance();
      }

      @Override
      public NetMessage build() {
        NetMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NetMessage buildPartial() {
        NetMessage result = new NetMessage(this);
        result.messageid_ = messageid_;
        result.messageseqid_ = messageseqid_;
        result.gamemoduleid_ = gamemoduleid_;
        result.errorcode_ = errorcode_;
        result.messagetype_ = messagetype_;
        result.sendtime_ = sendtime_;
        result.frommoduleid_ = frommoduleid_;
        result.tomoduleid_ = tomoduleid_;
        result.playerid_ = playerid_;
        result.clientip_ = clientip_;
        result.accountid_ = accountid_;
        result.secretkey_ = secretkey_;
        result.token_ = token_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetMessage) {
          return mergeFrom((NetMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetMessage other) {
        if (other == NetMessage.getDefaultInstance()) return this;
        if (!other.getMessageid().isEmpty()) {
          messageid_ = other.messageid_;
          onChanged();
        }
        if (!other.getMessageseqid().isEmpty()) {
          messageseqid_ = other.messageseqid_;
          onChanged();
        }
        if (!other.getGamemoduleid().isEmpty()) {
          gamemoduleid_ = other.gamemoduleid_;
          onChanged();
        }
        if (!other.getErrorcode().isEmpty()) {
          errorcode_ = other.errorcode_;
          onChanged();
        }
        if (!other.getMessagetype().isEmpty()) {
          messagetype_ = other.messagetype_;
          onChanged();
        }
        if (!other.getSendtime().isEmpty()) {
          sendtime_ = other.sendtime_;
          onChanged();
        }
        if (!other.getFrommoduleid().isEmpty()) {
          frommoduleid_ = other.frommoduleid_;
          onChanged();
        }
        if (!other.getTomoduleid().isEmpty()) {
          tomoduleid_ = other.tomoduleid_;
          onChanged();
        }
        if (!other.getPlayerid().isEmpty()) {
          playerid_ = other.playerid_;
          onChanged();
        }
        if (!other.getClientip().isEmpty()) {
          clientip_ = other.clientip_;
          onChanged();
        }
        if (!other.getAccountid().isEmpty()) {
          accountid_ = other.accountid_;
          onChanged();
        }
        if (!other.getSecretkey().isEmpty()) {
          secretkey_ = other.secretkey_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object messageid_ = "";
      /**
       * <pre>
       *ҵ�񷽷�messageid  ÿ��ҵ�񷽷�һ��messageid
       * </pre>
       *
       * <code>string messageid = 1;</code>
       */
      public String getMessageid() {
        Object ref = messageid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messageid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *ҵ�񷽷�messageid  ÿ��ҵ�񷽷�һ��messageid
       * </pre>
       *
       * <code>string messageid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageidBytes() {
        Object ref = messageid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ҵ�񷽷�messageid  ÿ��ҵ�񷽷�һ��messageid
       * </pre>
       *
       * <code>string messageid = 1;</code>
       */
      public Builder setMessageid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ҵ�񷽷�messageid  ÿ��ҵ�񷽷�һ��messageid
       * </pre>
       *
       * <code>string messageid = 1;</code>
       */
      public Builder clearMessageid() {
        
        messageid_ = getDefaultInstance().getMessageid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ҵ�񷽷�messageid  ÿ��ҵ�񷽷�һ��messageid
       * </pre>
       *
       * <code>string messageid = 1;</code>
       */
      public Builder setMessageidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageid_ = value;
        onChanged();
        return this;
      }

      private Object messageseqid_ = "";
      /**
       * <pre>
       *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
       * </pre>
       *
       * <code>string messageseqid = 2;</code>
       */
      public String getMessageseqid() {
        Object ref = messageseqid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messageseqid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
       * </pre>
       *
       * <code>string messageseqid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageseqidBytes() {
        Object ref = messageseqid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messageseqid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
       * </pre>
       *
       * <code>string messageseqid = 2;</code>
       */
      public Builder setMessageseqid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageseqid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
       * </pre>
       *
       * <code>string messageseqid = 2;</code>
       */
      public Builder clearMessageseqid() {
        
        messageseqid_ = getDefaultInstance().getMessageseqid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣmessageseqid  ÿ����Ϣһ��messageseqid
       * </pre>
       *
       * <code>string messageseqid = 2;</code>
       */
      public Builder setMessageseqidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageseqid_ = value;
        onChanged();
        return this;
      }

      private Object gamemoduleid_ = "";
      /**
       * <pre>
       *ÿ��ҵ��ϵͳһ��gamemoduleid        
       * </pre>
       *
       * <code>string gamemoduleid = 3;</code>
       */
      public String getGamemoduleid() {
        Object ref = gamemoduleid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gamemoduleid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳһ��gamemoduleid        
       * </pre>
       *
       * <code>string gamemoduleid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGamemoduleidBytes() {
        Object ref = gamemoduleid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gamemoduleid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳһ��gamemoduleid        
       * </pre>
       *
       * <code>string gamemoduleid = 3;</code>
       */
      public Builder setGamemoduleid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gamemoduleid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳһ��gamemoduleid        
       * </pre>
       *
       * <code>string gamemoduleid = 3;</code>
       */
      public Builder clearGamemoduleid() {
        
        gamemoduleid_ = getDefaultInstance().getGamemoduleid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳһ��gamemoduleid        
       * </pre>
       *
       * <code>string gamemoduleid = 3;</code>
       */
      public Builder setGamemoduleidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gamemoduleid_ = value;
        onChanged();
        return this;
      }

      private Object errorcode_ = "";
      /**
       * <pre>
       *������  
       * </pre>
       *
       * <code>string errorcode = 4;</code>
       */
      public String getErrorcode() {
        Object ref = errorcode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errorcode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *������  
       * </pre>
       *
       * <code>string errorcode = 4;</code>
       */
      public com.google.protobuf.ByteString
          getErrorcodeBytes() {
        Object ref = errorcode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorcode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *������  
       * </pre>
       *
       * <code>string errorcode = 4;</code>
       */
      public Builder setErrorcode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������  
       * </pre>
       *
       * <code>string errorcode = 4;</code>
       */
      public Builder clearErrorcode() {
        
        errorcode_ = getDefaultInstance().getErrorcode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *������  
       * </pre>
       *
       * <code>string errorcode = 4;</code>
       */
      public Builder setErrorcodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorcode_ = value;
        onChanged();
        return this;
      }

      private Object messagetype_ = "";
      /**
       * <pre>
       *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
       * </pre>
       *
       * <code>string messagetype = 5;</code>
       */
      public String getMessagetype() {
        Object ref = messagetype_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          messagetype_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
       * </pre>
       *
       * <code>string messagetype = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessagetypeBytes() {
        Object ref = messagetype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          messagetype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
       * </pre>
       *
       * <code>string messagetype = 5;</code>
       */
      public Builder setMessagetype(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messagetype_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
       * </pre>
       *
       * <code>string messagetype = 5;</code>
       */
      public Builder clearMessagetype() {
        
        messagetype_ = getDefaultInstance().getMessagetype();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ���� 1��֤��Ϣ  2������Ϣ   3������Ϣ
       * </pre>
       *
       * <code>string messagetype = 5;</code>
       */
      public Builder setMessagetypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messagetype_ = value;
        onChanged();
        return this;
      }

      private Object sendtime_ = "";
      /**
       * <pre>
       *����ʱ���
       * </pre>
       *
       * <code>string sendtime = 6;</code>
       */
      public String getSendtime() {
        Object ref = sendtime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sendtime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *����ʱ���
       * </pre>
       *
       * <code>string sendtime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSendtimeBytes() {
        Object ref = sendtime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sendtime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *����ʱ���
       * </pre>
       *
       * <code>string sendtime = 6;</code>
       */
      public Builder setSendtime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sendtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����ʱ���
       * </pre>
       *
       * <code>string sendtime = 6;</code>
       */
      public Builder clearSendtime() {
        
        sendtime_ = getDefaultInstance().getSendtime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *����ʱ���
       * </pre>
       *
       * <code>string sendtime = 6;</code>
       */
      public Builder setSendtimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sendtime_ = value;
        onChanged();
        return this;
      }

      private Object frommoduleid_ = "";
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
       * </pre>
       *
       * <code>string frommoduleid = 7;</code>
       */
      public String getFrommoduleid() {
        Object ref = frommoduleid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          frommoduleid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
       * </pre>
       *
       * <code>string frommoduleid = 7;</code>
       */
      public com.google.protobuf.ByteString
          getFrommoduleidBytes() {
        Object ref = frommoduleid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          frommoduleid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
       * </pre>
       *
       * <code>string frommoduleid = 7;</code>
       */
      public Builder setFrommoduleid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        frommoduleid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
       * </pre>
       *
       * <code>string frommoduleid = 7;</code>
       */
      public Builder clearFrommoduleid() {
        
        frommoduleid_ = getDefaultInstance().getFrommoduleid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� frommoduleid
       * </pre>
       *
       * <code>string frommoduleid = 7;</code>
       */
      public Builder setFrommoduleidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        frommoduleid_ = value;
        onChanged();
        return this;
      }

      private Object tomoduleid_ = "";
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
       * </pre>
       *
       * <code>string tomoduleid = 8;</code>
       */
      public String getTomoduleid() {
        Object ref = tomoduleid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tomoduleid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
       * </pre>
       *
       * <code>string tomoduleid = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTomoduleidBytes() {
        Object ref = tomoduleid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tomoduleid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
       * </pre>
       *
       * <code>string tomoduleid = 8;</code>
       */
      public Builder setTomoduleid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tomoduleid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
       * </pre>
       *
       * <code>string tomoduleid = 8;</code>
       */
      public Builder clearTomoduleid() {
        
        tomoduleid_ = getDefaultInstance().getTomoduleid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ÿ��ҵ��ϵͳ��һ��ʵ����Ӧһ�� tomoduleid  
       * </pre>
       *
       * <code>string tomoduleid = 8;</code>
       */
      public Builder setTomoduleidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tomoduleid_ = value;
        onChanged();
        return this;
      }

      private Object playerid_ = "";
      /**
       * <pre>
       *�û�id  
       * </pre>
       *
       * <code>string playerid = 9;</code>
       */
      public String getPlayerid() {
        Object ref = playerid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          playerid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *�û�id  
       * </pre>
       *
       * <code>string playerid = 9;</code>
       */
      public com.google.protobuf.ByteString
          getPlayeridBytes() {
        Object ref = playerid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          playerid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *�û�id  
       * </pre>
       *
       * <code>string playerid = 9;</code>
       */
      public Builder setPlayerid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        playerid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�û�id  
       * </pre>
       *
       * <code>string playerid = 9;</code>
       */
      public Builder clearPlayerid() {
        
        playerid_ = getDefaultInstance().getPlayerid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�û�id  
       * </pre>
       *
       * <code>string playerid = 9;</code>
       */
      public Builder setPlayeridBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        playerid_ = value;
        onChanged();
        return this;
      }

      private Object clientip_ = "";
      /**
       * <pre>
       *�ͻ���ip     
       * </pre>
       *
       * <code>string clientip = 10;</code>
       */
      public String getClientip() {
        Object ref = clientip_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *�ͻ���ip     
       * </pre>
       *
       * <code>string clientip = 10;</code>
       */
      public com.google.protobuf.ByteString
          getClientipBytes() {
        Object ref = clientip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *�ͻ���ip     
       * </pre>
       *
       * <code>string clientip = 10;</code>
       */
      public Builder setClientip(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ͻ���ip     
       * </pre>
       *
       * <code>string clientip = 10;</code>
       */
      public Builder clearClientip() {
        
        clientip_ = getDefaultInstance().getClientip();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *�ͻ���ip     
       * </pre>
       *
       * <code>string clientip = 10;</code>
       */
      public Builder setClientipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientip_ = value;
        onChanged();
        return this;
      }

      private Object accountid_ = "";
      /**
       * <pre>
       *ȫ���˺�id
       * </pre>
       *
       * <code>string accountid = 11;</code>
       */
      public String getAccountid() {
        Object ref = accountid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          accountid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *ȫ���˺�id
       * </pre>
       *
       * <code>string accountid = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAccountidBytes() {
        Object ref = accountid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          accountid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *ȫ���˺�id
       * </pre>
       *
       * <code>string accountid = 11;</code>
       */
      public Builder setAccountid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ȫ���˺�id
       * </pre>
       *
       * <code>string accountid = 11;</code>
       */
      public Builder clearAccountid() {
        
        accountid_ = getDefaultInstance().getAccountid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ȫ���˺�id
       * </pre>
       *
       * <code>string accountid = 11;</code>
       */
      public Builder setAccountidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountid_ = value;
        onChanged();
        return this;
      }

      private Object secretkey_ = "";
      /**
       * <pre>
       *��Ϣ������Կ
       * </pre>
       *
       * <code>string secretkey = 12;</code>
       */
      public String getSecretkey() {
        Object ref = secretkey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          secretkey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��Ϣ������Կ
       * </pre>
       *
       * <code>string secretkey = 12;</code>
       */
      public com.google.protobuf.ByteString
          getSecretkeyBytes() {
        Object ref = secretkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          secretkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��Ϣ������Կ
       * </pre>
       *
       * <code>string secretkey = 12;</code>
       */
      public Builder setSecretkey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secretkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ������Կ
       * </pre>
       *
       * <code>string secretkey = 12;</code>
       */
      public Builder clearSecretkey() {
        
        secretkey_ = getDefaultInstance().getSecretkey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣ������Կ
       * </pre>
       *
       * <code>string secretkey = 12;</code>
       */
      public Builder setSecretkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secretkey_ = value;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 13;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 13;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 13;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 13;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 13;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private Object body_ = "";
      /**
       * <pre>
       *json��ʽ����Ϣ��
       * </pre>
       *
       * <code>string body = 14;</code>
       */
      public String getBody() {
        Object ref = body_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *json��ʽ����Ϣ��
       * </pre>
       *
       * <code>string body = 14;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *json��ʽ����Ϣ��
       * </pre>
       *
       * <code>string body = 14;</code>
       */
      public Builder setBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *json��ʽ����Ϣ��
       * </pre>
       *
       * <code>string body = 14;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *json��ʽ����Ϣ��
       * </pre>
       *
       * <code>string body = 14;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NetMessage)
    }

    // @@protoc_insertion_point(class_scope:NetMessage)
    private static final NetMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NetMessage();
    }

    public static NetMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetMessage>
        PARSER = new com.google.protobuf.AbstractParser<NetMessage>() {
      @Override
      public NetMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NetMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public NetMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NetMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020NetMessage.proto\"\226\002\n\nNetMessage\022\021\n\tmes" +
      "sageid\030\001 \001(\t\022\024\n\014messageseqid\030\002 \001(\t\022\024\n\014ga" +
      "memoduleid\030\003 \001(\t\022\021\n\terrorcode\030\004 \001(\t\022\023\n\013m" +
      "essagetype\030\005 \001(\t\022\020\n\010sendtime\030\006 \001(\t\022\024\n\014fr" +
      "ommoduleid\030\007 \001(\t\022\022\n\ntomoduleid\030\010 \001(\t\022\020\n\010" +
      "playerid\030\t \001(\t\022\020\n\010clientip\030\n \001(\t\022\021\n\tacco" +
      "untid\030\013 \001(\t\022\021\n\tsecretkey\030\014 \001(\t\022\r\n\005token\030" +
      "\r \001(\t\022\014\n\004body\030\016 \001(\tB\"\n\027com.network.messa" +
      "ge.webB\007Messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NetMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NetMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NetMessage_descriptor,
        new String[] { "Messageid", "Messageseqid", "Gamemoduleid", "Errorcode", "Messagetype", "Sendtime", "Frommoduleid", "Tomoduleid", "Playerid", "Clientip", "Accountid", "Secretkey", "Token", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
